/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco.vista;

import java.util.*;
import banco.modelo.*;
import javax.swing.JInternalFrame;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author forta
 */
public class NuevoMovimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoMovimiento
     */
    
    
   
    public NuevoMovimiento() {
        initComponents();
       
         
       jLabel2.setVisible(false);
       jLabel3.setVisible(false);
       jLabel4.setVisible(false);
       jLabel5.setVisible(false);
       jLabel6.setVisible(false);
       jLabel7.setVisible(false);
       jLabel8.setVisible(false);
       jTextField1.setVisible(false);
       jTextField2.setVisible(false);
       jTextField3.setVisible(false);
       jTextField4.setVisible(false);
       jTextField5.setVisible(false);
       jComboBox1.setVisible(false);
       jComboBox3.setVisible(false);
       jButton1.setVisible(false);
    
    }
   
    
    
     public void obtenerDatos(){
        
       List<Cuenta> cuentas = new DAOCuenta().obtenerRegistros();
       jComboBox1.addItem("");
       jComboBox3.addItem("");
      
       for (Cuenta cuenta : cuentas){
            jComboBox1.addItem(cuenta);
            jComboBox3.addItem(cuenta);
            
        }
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Movimientos");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar....", "Deposito", "Retiro", "Transferir" }));
        jComboBox2.setToolTipText("");
        jComboBox2.setName(""); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Accion a Realizar");

        jLabel2.setText("No de cuenta origen");

        jTextField1.setToolTipText("");

        jLabel3.setText("Nombre");

        jLabel4.setText("Tipo de Cuenta");

        jLabel5.setText("No de cuenta destino");

        jLabel6.setText("Nombre");

        jLabel7.setText("Tipo de Cuenta");

        jLabel8.setText("Monto a Transferir");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, 0, 176, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      if(jComboBox1.getSelectedIndex() > 0){
            Cuenta cuenta = (Cuenta)jComboBox1.getSelectedItem();
            jTextField1.setText(cuenta.getCliente().getNombre());
            jTextField2.setText(cuenta.getTipo());
           
        }
        else{
            jTextField1.setText("");
            jTextField2.setText("");
           
        }
           
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
        // TODO add your handling code here:
        
     
       
       if(jComboBox2.getSelectedItem().equals("Seleccionar....")){
       jLabel2.setVisible(false);
       jLabel3.setVisible(false);
       jLabel4.setVisible(false);
       jLabel5.setVisible(false);
       jLabel6.setVisible(false);
       jLabel7.setVisible(false);
       jLabel8.setVisible(false);
       jTextField1.setVisible(false);
       jTextField2.setVisible(false);
       jTextField3.setVisible(false);
       jTextField4.setVisible(false);
       jTextField5.setVisible(false);
       jComboBox1.setVisible(false);
       jComboBox3.setVisible(false);
       jButton1.setVisible(false);
       }
        
       if(jComboBox2.getSelectedItem().equals("Transferir")){
         
       jLabel2.setVisible(true);
       jLabel3.setVisible(true);
       jLabel4.setVisible(true);
       jLabel5.setVisible(true);
       jLabel6.setVisible(true);
       jLabel7.setVisible(true);
       jLabel8.setVisible(true);
       jTextField1.setVisible(true);
       jTextField2.setVisible(true);
       jTextField3.setVisible(true);
       jTextField4.setVisible(true);
       jTextField5.setVisible(true);
       jComboBox1.setVisible(true);
       jComboBox3.setVisible(true);
       jButton1.setVisible(true);
       }
       
       if(jComboBox2.getSelectedItem().equals("Deposito")){
       jLabel2.setText("No Cuenta");
       jLabel2.setVisible(true);
       jLabel3.setVisible(true);
       jLabel4.setVisible(true);
       jLabel8.setText("Monto a Depositar");
       jLabel8.setVisible(true);
       jTextField1.setVisible(true);
       jTextField2.setVisible(true);
      
       jTextField5.setVisible(true);
       jComboBox1.setVisible(true);
       
       jButton1.setVisible(true);
       }
       
       if(jComboBox2.getSelectedItem().equals("Retiro")){
       jLabel2.setText("No Cuenta");
       jLabel2.setVisible(true);
       jLabel3.setVisible(true);
       jLabel4.setVisible(true);
       jLabel8.setText("Monto a Retirar");
       jLabel8.setVisible(true);
       jTextField1.setVisible(true);
       jTextField2.setVisible(true);
      
       jTextField5.setVisible(true);
       jComboBox1.setVisible(true);
       
       jButton1.setVisible(true);
       }
       
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
         if(jComboBox3.getSelectedIndex() > 0){
            Cuenta cuenta = (Cuenta)jComboBox3.getSelectedItem();
            jTextField3.setText(cuenta.getCliente().getNombre());
            jTextField4.setText(cuenta.getTipo());
           
        }
        else{
            jTextField3.setText("");
            jTextField4.setText("");
           
        }

    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                
        int no_cuenta = jComboBox1.getSelectedIndex();
        int no_cuentadestino = jComboBox3.getSelectedIndex();
        String monto = jTextField5.getText();
        
        if(jComboBox2.getSelectedItem().equals("Transferir")){
        if(String.valueOf(no_cuenta).equals("") ||String.valueOf(no_cuentadestino).equals("") || monto.equals("")){
            JOptionPane.showMessageDialog(rootPane,"Hay campos vacios");
            return;
        }
         
         boolean res = new DAOMovimiento().Transferir(no_cuenta,no_cuentadestino,Double.parseDouble(monto));
        if(!res){
            JOptionPane.showMessageDialog(rootPane,"Trasnferencia Realizada");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            
            jComboBox1.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jComboBox1.setVisible(false);
            jComboBox3.setVisible(false);
            jButton1.setVisible(false);
         
            }
        }
        
        if(jComboBox2.getSelectedItem().equals("Deposito")){
        
            
        if(String.valueOf(no_cuenta).equals("") || monto.equals("")){
            JOptionPane.showMessageDialog(rootPane,"Hay campos vacios");
            return;
        }
         
         boolean res = new DAOMovimiento().Deposito(Double.parseDouble(monto),no_cuenta);
        if(!res){
            JOptionPane.showMessageDialog(rootPane,"Deposito Realizada");
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField5.setText("");
            
            jComboBox1.setSelectedIndex(0);
            
            
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
           
            jLabel8.setVisible(false);
            
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
      
            jTextField5.setVisible(false);
            jComboBox1.setVisible(false);
       
            jButton1.setVisible(false);
         
            }
        }
        
        if(jComboBox2.getSelectedItem().equals("Retiro")){
        if(String.valueOf(no_cuenta).equals("") || monto.equals("")){
            JOptionPane.showMessageDialog(rootPane,"Hay campos vacios");
            return;
        }
         
         boolean res = new DAOMovimiento().Retiro(Double.parseDouble(monto)*-1,no_cuenta);
        if(!res){
            JOptionPane.showMessageDialog(rootPane,"Retiro Realizada");
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField5.setText("");
            
            jComboBox1.setSelectedIndex(0);
            
            
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
           
            jLabel8.setVisible(false);
            
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
      
            jTextField5.setVisible(false);
            jComboBox1.setVisible(false);
       
            jButton1.setVisible(false);
         
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private Object getSelectedIndex() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
